spellername = "Ojibwa"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Ojibwa spellchecker"
oj = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Ojibwa, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
oj = "TRANSLATE: A spellchecker for Ojibwa, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.oj"

[windows]
system_product_code = "{8139AB0A-00F2-4CC7-825E-F749A8B11A9B}_is1"
legacy_product_codes = [
    { value = "01789212-1A5F-4C16-9672-59835CF258C4", kind = "nsis" },
    { value = "C3DD383C-3132-4A05-9382-04C60EC40702", kind = "nsis" }
]
