template = "https://github.com/giellalt/template-lang-und"
rev_id = 295
template_sha = "9e160f410d669a53f8b740a218fd6462f17d3234"

[replacements]
__GLOTTOLOG_ID__ = "cent2136"
__REPO__ = "lang-oji"
__UND2C__ = "oj"
__UNDEFINED__ = "Ojibwa"
__UND__ = "oji"
